# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Admin(object):
    def setupUi(self, Admin):
        Admin.setObjectName(_fromUtf8("Admin"))
        Admin.resize(795, 573)
        Admin.setStyleSheet(_fromUtf8("QMainWindow{\n"
"background-image: url(\"/home/jimz/Downloads/Ingenieria_Software/fondoVet2.jpg\");\n"
"}\n"
"QLineEdit{\n"
"background-color: #ffffff;\n"
"}\n"
"QComboBox{\n"
"background-color: #ffffff;\n"
"}\n"
"QPushButton{\n"
"background: #bbcbe5;\n"
"}\n"
""))
        self.centralwidget = QtGui.QWidget(Admin)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label_18 = QtGui.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(68, 29, 37, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.nameALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.nameALineEdit.setGeometry(QtCore.QRect(140, 30, 133, 20))
        self.nameALineEdit.setAccessibleDescription(_fromUtf8(""))
        self.nameALineEdit.setAutoFillBackground(False)
        self.nameALineEdit.setText(_fromUtf8(""))
        self.nameALineEdit.setFrame(False)
        self.nameALineEdit.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.nameALineEdit.setObjectName(_fromUtf8("nameALineEdit"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(389, 29, 65, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.idALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.idALineEdit.setGeometry(QtCore.QRect(470, 30, 133, 20))
        self.idALineEdit.setFrame(False)
        self.idALineEdit.setObjectName(_fromUtf8("idALineEdit"))
        self.entryAPushButton = QtGui.QPushButton(self.centralwidget)
        self.entryAPushButton.setGeometry(QtCore.QRect(700, 30, 81, 51))
        self.entryAPushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.entryAPushButton.setStyleSheet(_fromUtf8(""))
        self.entryAPushButton.setAutoDefault(True)
        self.entryAPushButton.setObjectName(_fromUtf8("entryAPushButton"))
        self.label_17 = QtGui.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(68, 69, 46, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lastname1ALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lastname1ALineEdit.setGeometry(QtCore.QRect(140, 70, 133, 20))
        self.lastname1ALineEdit.setFrame(False)
        self.lastname1ALineEdit.setObjectName(_fromUtf8("lastname1ALineEdit"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(389, 69, 20, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.rfcALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.rfcALineEdit.setGeometry(QtCore.QRect(470, 70, 133, 20))
        self.rfcALineEdit.setFrame(False)
        self.rfcALineEdit.setObjectName(_fromUtf8("rfcALineEdit"))
        self.editAPushButton = QtGui.QPushButton(self.centralwidget)
        self.editAPushButton.setGeometry(QtCore.QRect(700, 90, 81, 51))
        self.editAPushButton.setStyleSheet(_fromUtf8(""))
        self.editAPushButton.setAutoDefault(True)
        self.editAPushButton.setObjectName(_fromUtf8("editAPushButton"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(68, 109, 46, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lastname2ALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lastname2ALineEdit.setGeometry(QtCore.QRect(140, 110, 133, 20))
        self.lastname2ALineEdit.setFrame(False)
        self.lastname2ALineEdit.setObjectName(_fromUtf8("lastname2ALineEdit"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(389, 111, 41, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.phoneALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.phoneALineEdit.setGeometry(QtCore.QRect(470, 112, 133, 20))
        self.phoneALineEdit.setFrame(False)
        self.phoneALineEdit.setObjectName(_fromUtf8("phoneALineEdit"))
        self.deleteAPushButton = QtGui.QPushButton(self.centralwidget)
        self.deleteAPushButton.setGeometry(QtCore.QRect(700, 150, 81, 51))
        self.deleteAPushButton.setStyleSheet(_fromUtf8(""))
        self.deleteAPushButton.setAutoDefault(True)
        self.deleteAPushButton.setObjectName(_fromUtf8("deleteAPushButton"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(68, 150, 43, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.addressALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.addressALineEdit.setGeometry(QtCore.QRect(140, 150, 133, 20))
        self.addressALineEdit.setFrame(False)
        self.addressALineEdit.setObjectName(_fromUtf8("addressALineEdit"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(389, 150, 62, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.orgAComboBox = QtGui.QComboBox(self.centralwidget)
        self.orgAComboBox.setGeometry(QtCore.QRect(470, 150, 131, 20))
        self.orgAComboBox.setFrame(False)
        self.orgAComboBox.setObjectName(_fromUtf8("orgAComboBox"))
        self.orgAComboBox.addItem(_fromUtf8(""))
        self.orgAComboBox.addItem(_fromUtf8(""))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(68, 190, 19, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.nssALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.nssALineEdit.setGeometry(QtCore.QRect(140, 190, 133, 20))
        self.nssALineEdit.setFrame(False)
        self.nssALineEdit.setObjectName(_fromUtf8("nssALineEdit"))
        self.searchALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.searchALineEdit.setGeometry(QtCore.QRect(470, 230, 131, 31))
        self.searchALineEdit.setFrame(False)
        self.searchALineEdit.setObjectName(_fromUtf8("searchALineEdit"))
        self.registerATableWidget = QtGui.QTableWidget(self.centralwidget)
        self.registerATableWidget.setGeometry(QtCore.QRect(60, 270, 621, 241))
        self.registerATableWidget.setStyleSheet(_fromUtf8(""))
        self.registerATableWidget.setFrameShape(QtGui.QFrame.Box)
        self.registerATableWidget.setFrameShadow(QtGui.QFrame.Plain)
        self.registerATableWidget.setObjectName(_fromUtf8("registerATableWidget"))
        self.registerATableWidget.setColumnCount(10)
        self.registerATableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.registerATableWidget.setHorizontalHeaderItem(9, item)
        self.passALineEdit = QtGui.QLineEdit(self.centralwidget)
        self.passALineEdit.setGeometry(QtCore.QRect(470, 190, 131, 20))
        self.passALineEdit.setFrame(False)
        self.passALineEdit.setObjectName(_fromUtf8("passALineEdit"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 190, 51, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.clearAPushButton = QtGui.QPushButton(self.centralwidget)
        self.clearAPushButton.setGeometry(QtCore.QRect(700, 210, 81, 51))
        self.clearAPushButton.setStyleSheet(_fromUtf8(""))
        self.clearAPushButton.setAutoDefault(True)
        self.clearAPushButton.setObjectName(_fromUtf8("clearAPushButton"))
        Admin.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(Admin)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        Admin.setStatusBar(self.statusbar)
        self.actionCambiar_sesion = QtGui.QAction(Admin)
        self.actionCambiar_sesion.setObjectName(_fromUtf8("actionCambiar_sesion"))
        self.actionCerrar = QtGui.QAction(Admin)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))

        self.retranslateUi(Admin)
        QtCore.QMetaObject.connectSlotsByName(Admin)
        Admin.setTabOrder(self.nameALineEdit, self.lastname1ALineEdit)
        Admin.setTabOrder(self.lastname1ALineEdit, self.lastname2ALineEdit)
        Admin.setTabOrder(self.lastname2ALineEdit, self.addressALineEdit)
        Admin.setTabOrder(self.addressALineEdit, self.nssALineEdit)
        Admin.setTabOrder(self.nssALineEdit, self.idALineEdit)
        Admin.setTabOrder(self.idALineEdit, self.rfcALineEdit)
        Admin.setTabOrder(self.rfcALineEdit, self.phoneALineEdit)
        Admin.setTabOrder(self.phoneALineEdit, self.orgAComboBox)
        Admin.setTabOrder(self.orgAComboBox, self.entryAPushButton)
        Admin.setTabOrder(self.entryAPushButton, self.editAPushButton)
        Admin.setTabOrder(self.editAPushButton, self.deleteAPushButton)
        Admin.setTabOrder(self.deleteAPushButton, self.searchALineEdit)
        Admin.setTabOrder(self.searchALineEdit, self.registerATableWidget)

    def retranslateUi(self, Admin):
        Admin.setWindowTitle(_translate("Admin", "Registro", None))
        self.label_18.setText(_translate("Admin", "Nombre", None))
        self.label_5.setText(_translate("Admin", "ID trabajador", None))
        self.entryAPushButton.setText(_translate("Admin", "Ingresar", None))
        self.label_17.setText(_translate("Admin", "Apellido 1", None))
        self.label_6.setText(_translate("Admin", "RFC", None))
        self.editAPushButton.setText(_translate("Admin", "Editar", None))
        self.label_3.setText(_translate("Admin", "Apellido 2", None))
        self.label_7.setText(_translate("Admin", "Telefono", None))
        self.deleteAPushButton.setText(_translate("Admin", "Eliminar", None))
        self.label_4.setText(_translate("Admin", "Direccion", None))
        self.label_8.setText(_translate("Admin", "Organizacion", None))
        self.orgAComboBox.setItemText(0, _translate("Admin", "Veterinaria", None))
        self.orgAComboBox.setItemText(1, _translate("Admin", "Refugio", None))
        self.label_9.setText(_translate("Admin", "NSS", None))
        self.searchALineEdit.setText(_translate("Admin", "Buscar", None))
        item = self.registerATableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Admin", "Nombre", None))
        item = self.registerATableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Admin", "Apellido1", None))
        item = self.registerATableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Admin", "Apellido2", None))
        item = self.registerATableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Admin", "Direccion", None))
        item = self.registerATableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Admin", "NSS", None))
        item = self.registerATableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Admin", "ID trabajador", None))
        item = self.registerATableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Admin", "RFC", None))
        item = self.registerATableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Admin", "Telefono", None))
        item = self.registerATableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Admin", "Organizacion", None))
        item = self.registerATableWidget.horizontalHeaderItem(9)
        item.setText(_translate("Admin", "Password", None))
        self.label.setText(_translate("Admin", "Password", None))
        self.clearAPushButton.setText(_translate("Admin", "Limpiar", None))
        self.actionCambiar_sesion.setText(_translate("Admin", "Cambiar sesion", None))
        self.actionCerrar.setText(_translate("Admin", "Cerrar", None))


class Admin(QtGui.QMainWindow, Ui_Admin):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

