# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'veterinary.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_veterinary(object):
    def setupUi(self, veterinary):
        veterinary.setObjectName(_fromUtf8("veterinary"))
        veterinary.setWindowModality(QtCore.Qt.NonModal)
        veterinary.resize(801, 574)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../prize-badge-with-paw-print.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        veterinary.setWindowIcon(icon)
        veterinary.setAutoFillBackground(False)
        veterinary.setStyleSheet(_fromUtf8("#veterinary{\n"
"\n"
"}"))
        self.centralwidget = QtGui.QWidget(veterinary)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.TabWidget_4 = QtGui.QTabWidget(self.centralwidget)
        self.TabWidget_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.TabWidget_4.setStyleSheet(_fromUtf8("QWidget{\n"
"    background-image: url(\"/home/jimz/Downloads/Ingenieria_Software/fondoVet2.jpg\");\n"
"}\n"
"QLineEdit{\n"
"    background: #ffffff;\n"
"    \n"
"}\n"
"QLabel{\n"
"    background: rgba(255, 255, 255, 0); \n"
"}\n"
"QTableWidget{\n"
"    background: #ffffff;\n"
"}\n"
"QPushButton{\n"
"    background: #bbcbe5;\n"
"}"))
        self.TabWidget_4.setTabShape(QtGui.QTabWidget.Rounded)
        self.TabWidget_4.setElideMode(QtCore.Qt.ElideNone)
        self.TabWidget_4.setObjectName(_fromUtf8("TabWidget_4"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.registerCTableWidget = QtGui.QTableWidget(self.tab_1)
        self.registerCTableWidget.setEnabled(True)
        self.registerCTableWidget.setGeometry(QtCore.QRect(82, 189, 661, 281))
        self.registerCTableWidget.setFrameShape(QtGui.QFrame.Box)
        self.registerCTableWidget.setLineWidth(1)
        self.registerCTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.registerCTableWidget.setObjectName(_fromUtf8("registerCTableWidget"))
        self.registerCTableWidget.setColumnCount(9)
        self.registerCTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.registerCTableWidget.setHorizontalHeaderItem(8, item)
        self.registerCTableWidget.horizontalHeader().setVisible(True)
        self.registerCTableWidget.horizontalHeader().setDefaultSectionSize(125)
        self.registerCTableWidget.horizontalHeader().setHighlightSections(True)
        self.registerCTableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.registerCTableWidget.verticalHeader().setVisible(False)
        self.registerCTableWidget.verticalHeader().setHighlightSections(False)
        self.label_18 = QtGui.QLabel(self.tab_1)
        self.label_18.setGeometry(QtCore.QRect(82, 9, 52, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.nameCLineEdit = QtGui.QLineEdit(self.tab_1)
        self.nameCLineEdit.setGeometry(QtCore.QRect(160, 9, 127, 23))
        self.nameCLineEdit.setFrame(False)
        self.nameCLineEdit.setObjectName(_fromUtf8("nameCLineEdit"))
        self.label_5 = QtGui.QLabel(self.tab_1)
        self.label_5.setGeometry(QtCore.QRect(350, 10, 21, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cpCLineEdit = QtGui.QLineEdit(self.tab_1)
        self.cpCLineEdit.setGeometry(QtCore.QRect(410, 10, 127, 23))
        self.cpCLineEdit.setFrame(False)
        self.cpCLineEdit.setObjectName(_fromUtf8("cpCLineEdit"))
        self.entryCPushButton = QtGui.QPushButton(self.tab_1)
        self.entryCPushButton.setGeometry(QtCore.QRect(580, 10, 71, 51))
        self.entryCPushButton.setAutoDefault(True)
        self.entryCPushButton.setObjectName(_fromUtf8("entryCPushButton"))
        self.lastname1CLineEdit = QtGui.QLineEdit(self.tab_1)
        self.lastname1CLineEdit.setGeometry(QtCore.QRect(160, 38, 127, 23))
        self.lastname1CLineEdit.setFrame(False)
        self.lastname1CLineEdit.setObjectName(_fromUtf8("lastname1CLineEdit"))
        self.label_17 = QtGui.QLabel(self.tab_1)
        self.label_17.setGeometry(QtCore.QRect(82, 38, 62, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.emailCLineEdit = QtGui.QLineEdit(self.tab_1)
        self.emailCLineEdit.setGeometry(QtCore.QRect(410, 39, 127, 23))
        self.emailCLineEdit.setFrame(False)
        self.emailCLineEdit.setObjectName(_fromUtf8("emailCLineEdit"))
        self.label_6 = QtGui.QLabel(self.tab_1)
        self.label_6.setGeometry(QtCore.QRect(350, 39, 40, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_3 = QtGui.QLabel(self.tab_1)
        self.label_3.setGeometry(QtCore.QRect(82, 67, 62, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lastname2CLineEdit = QtGui.QLineEdit(self.tab_1)
        self.lastname2CLineEdit.setGeometry(QtCore.QRect(160, 68, 127, 23))
        self.lastname2CLineEdit.setFrame(False)
        self.lastname2CLineEdit.setObjectName(_fromUtf8("lastname2CLineEdit"))
        self.phoneCLineEdit = QtGui.QLineEdit(self.tab_1)
        self.phoneCLineEdit.setGeometry(QtCore.QRect(410, 69, 127, 23))
        self.phoneCLineEdit.setFrame(False)
        self.phoneCLineEdit.setObjectName(_fromUtf8("phoneCLineEdit"))
        self.label_7 = QtGui.QLabel(self.tab_1)
        self.label_7.setGeometry(QtCore.QRect(350, 68, 54, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.addressCLineEdit = QtGui.QLineEdit(self.tab_1)
        self.addressCLineEdit.setGeometry(QtCore.QRect(160, 99, 127, 23))
        self.addressCLineEdit.setFrame(False)
        self.addressCLineEdit.setObjectName(_fromUtf8("addressCLineEdit"))
        self.label_4 = QtGui.QLabel(self.tab_1)
        self.label_4.setGeometry(QtCore.QRect(82, 98, 59, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.celphoneCLineEdit = QtGui.QLineEdit(self.tab_1)
        self.celphoneCLineEdit.setGeometry(QtCore.QRect(160, 130, 127, 23))
        self.celphoneCLineEdit.setFrame(False)
        self.celphoneCLineEdit.setObjectName(_fromUtf8("celphoneCLineEdit"))
        self.label_9 = QtGui.QLabel(self.tab_1)
        self.label_9.setGeometry(QtCore.QRect(82, 129, 44, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.searchCLineEdit = QtGui.QLineEdit(self.tab_1)
        self.searchCLineEdit.setGeometry(QtCore.QRect(410, 140, 131, 31))
        self.searchCLineEdit.setFrame(False)
        self.searchCLineEdit.setObjectName(_fromUtf8("searchCLineEdit"))
        self.editCPushButton = QtGui.QPushButton(self.tab_1)
        self.editCPushButton.setGeometry(QtCore.QRect(670, 10, 71, 51))
        self.editCPushButton.setAutoDefault(True)
        self.editCPushButton.setObjectName(_fromUtf8("editCPushButton"))
        self.deleteCPushButton = QtGui.QPushButton(self.tab_1)
        self.deleteCPushButton.setGeometry(QtCore.QRect(670, 80, 71, 51))
        self.deleteCPushButton.setAutoDefault(True)
        self.deleteCPushButton.setObjectName(_fromUtf8("deleteCPushButton"))
        self.clearCPushButton = QtGui.QPushButton(self.tab_1)
        self.clearCPushButton.setGeometry(QtCore.QRect(580, 80, 71, 51))
        self.clearCPushButton.setObjectName(_fromUtf8("clearCPushButton"))
        self.TabWidget_4.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.ageDLineEdit = QtGui.QLineEdit(self.tab_2)
        self.ageDLineEdit.setGeometry(QtCore.QRect(340, 109, 131, 23))
        self.ageDLineEdit.setFrame(False)
        self.ageDLineEdit.setObjectName(_fromUtf8("ageDLineEdit"))
        self.imageDLabel = QtGui.QLabel(self.tab_2)
        self.imageDLabel.setGeometry(QtCore.QRect(80, 40, 211, 191))
        self.imageDLabel.setStyleSheet(_fromUtf8("border-radius: 5px;\n"
"border: 2px solid black;\n"
"background: #ffffff;"))
        self.imageDLabel.setFrameShape(QtGui.QFrame.Box)
        self.imageDLabel.setFrameShadow(QtGui.QFrame.Plain)
        self.imageDLabel.setText(_fromUtf8(""))
        self.imageDLabel.setObjectName(_fromUtf8("imageDLabel"))
        self.entryDPushButton = QtGui.QPushButton(self.tab_2)
        self.entryDPushButton.setGeometry(QtCore.QRect(540, 50, 71, 51))
        self.entryDPushButton.setAutoDefault(True)
        self.entryDPushButton.setObjectName(_fromUtf8("entryDPushButton"))
        self.nameOwnerDComboBox = QtGui.QComboBox(self.tab_2)
        self.nameOwnerDComboBox.setGeometry(QtCore.QRect(340, 170, 131, 21))
        self.nameOwnerDComboBox.setFrame(False)
        self.nameOwnerDComboBox.setObjectName(_fromUtf8("nameOwnerDComboBox"))
        self.deleteDPushButton = QtGui.QPushButton(self.tab_2)
        self.deleteDPushButton.setGeometry(QtCore.QRect(630, 140, 71, 51))
        self.deleteDPushButton.setAutoDefault(True)
        self.deleteDPushButton.setObjectName(_fromUtf8("deleteDPushButton"))
        self.raceDLineEdit = QtGui.QLineEdit(self.tab_2)
        self.raceDLineEdit.setGeometry(QtCore.QRect(340, 79, 131, 23))
        self.raceDLineEdit.setFrame(False)
        self.raceDLineEdit.setObjectName(_fromUtf8("raceDLineEdit"))
        self.genderDLineEdit = QtGui.QLineEdit(self.tab_2)
        self.genderDLineEdit.setGeometry(QtCore.QRect(340, 139, 131, 23))
        self.genderDLineEdit.setFrame(False)
        self.genderDLineEdit.setObjectName(_fromUtf8("genderDLineEdit"))
        self.editDPushButton = QtGui.QPushButton(self.tab_2)
        self.editDPushButton.setGeometry(QtCore.QRect(630, 50, 71, 51))
        self.editDPushButton.setAutoDefault(True)
        self.editDPushButton.setObjectName(_fromUtf8("editDPushButton"))
        self.uploadDPushButton = QtGui.QPushButton(self.tab_2)
        self.uploadDPushButton.setGeometry(QtCore.QRect(370, 210, 71, 51))
        self.uploadDPushButton.setObjectName(_fromUtf8("uploadDPushButton"))
        self.registerDTableWidget = QtGui.QTableWidget(self.tab_2)
        self.registerDTableWidget.setGeometry(QtCore.QRect(49, 271, 691, 211))
        self.registerDTableWidget.setFrameShape(QtGui.QFrame.Box)
        self.registerDTableWidget.setObjectName(_fromUtf8("registerDTableWidget"))
        self.registerDTableWidget.setColumnCount(6)
        self.registerDTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.registerDTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.registerDTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.registerDTableWidget.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.registerDTableWidget.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.registerDTableWidget.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.registerDTableWidget.setHorizontalHeaderItem(5, item)
        self.registerDTableWidget.horizontalHeader().setDefaultSectionSize(128)
        self.registerDTableWidget.verticalHeader().setVisible(False)
        self.registerDTableWidget.verticalHeader().setHighlightSections(False)
        self.searchDLineEdit = QtGui.QLineEdit(self.tab_2)
        self.searchDLineEdit.setGeometry(QtCore.QRect(560, 220, 131, 31))
        self.searchDLineEdit.setFrame(False)
        self.searchDLineEdit.setObjectName(_fromUtf8("searchDLineEdit"))
        self.nameDogDLineEdit = QtGui.QLineEdit(self.tab_2)
        self.nameDogDLineEdit.setGeometry(QtCore.QRect(340, 49, 131, 23))
        self.nameDogDLineEdit.setFrame(False)
        self.nameDogDLineEdit.setObjectName(_fromUtf8("nameDogDLineEdit"))
        self.clearDPushButton = QtGui.QPushButton(self.tab_2)
        self.clearDPushButton.setGeometry(QtCore.QRect(540, 140, 71, 51))
        self.clearDPushButton.setObjectName(_fromUtf8("clearDPushButton"))
        self.TabWidget_4.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.chatLineEdit = QtGui.QLineEdit(self.tab_3)
        self.chatLineEdit.setGeometry(QtCore.QRect(110, 430, 551, 41))
        self.chatLineEdit.setAutoFillBackground(False)
        self.chatLineEdit.setStyleSheet(_fromUtf8("border-radius: 5px;\n"
"border: 2px solid black;"))
        self.chatLineEdit.setText(_fromUtf8(""))
        self.chatLineEdit.setFrame(True)
        self.chatLineEdit.setObjectName(_fromUtf8("chatLineEdit"))
        self.chatTextBrowser = QtGui.QTextBrowser(self.tab_3)
        self.chatTextBrowser.setGeometry(QtCore.QRect(30, 20, 711, 391))
        self.chatTextBrowser.setStyleSheet(_fromUtf8("border-radius: 5px;\n"
"border: 2px solid black;\n"
"background: #ffffff;"))
        self.chatTextBrowser.setFrameShape(QtGui.QFrame.Box)
        self.chatTextBrowser.setFrameShadow(QtGui.QFrame.Plain)
        self.chatTextBrowser.setObjectName(_fromUtf8("chatTextBrowser"))
        self.TabWidget_4.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout.addWidget(self.TabWidget_4, 0, 1, 1, 1)
        veterinary.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(veterinary)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        veterinary.setStatusBar(self.statusbar)
        self.actionCerrar_sesion = QtGui.QAction(veterinary)
        self.actionCerrar_sesion.setObjectName(_fromUtf8("actionCerrar_sesion"))
        self.actionCerrar = QtGui.QAction(veterinary)
        self.actionCerrar.setObjectName(_fromUtf8("actionCerrar"))

        self.retranslateUi(veterinary)
        self.TabWidget_4.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(veterinary)
        veterinary.setTabOrder(self.nameCLineEdit, self.lastname1CLineEdit)
        veterinary.setTabOrder(self.lastname1CLineEdit, self.lastname2CLineEdit)
        veterinary.setTabOrder(self.lastname2CLineEdit, self.addressCLineEdit)
        veterinary.setTabOrder(self.addressCLineEdit, self.celphoneCLineEdit)
        veterinary.setTabOrder(self.celphoneCLineEdit, self.cpCLineEdit)
        veterinary.setTabOrder(self.cpCLineEdit, self.emailCLineEdit)
        veterinary.setTabOrder(self.emailCLineEdit, self.phoneCLineEdit)
        veterinary.setTabOrder(self.phoneCLineEdit, self.searchCLineEdit)
        veterinary.setTabOrder(self.searchCLineEdit, self.entryCPushButton)
        veterinary.setTabOrder(self.entryCPushButton, self.editCPushButton)
        veterinary.setTabOrder(self.editCPushButton, self.deleteCPushButton)
        veterinary.setTabOrder(self.deleteCPushButton, self.registerCTableWidget)
        veterinary.setTabOrder(self.registerCTableWidget, self.searchDLineEdit)
        veterinary.setTabOrder(self.searchDLineEdit, self.nameDogDLineEdit)
        veterinary.setTabOrder(self.nameDogDLineEdit, self.raceDLineEdit)
        veterinary.setTabOrder(self.raceDLineEdit, self.ageDLineEdit)
        veterinary.setTabOrder(self.ageDLineEdit, self.genderDLineEdit)
        veterinary.setTabOrder(self.genderDLineEdit, self.nameOwnerDComboBox)
        veterinary.setTabOrder(self.nameOwnerDComboBox, self.uploadDPushButton)
        veterinary.setTabOrder(self.uploadDPushButton, self.entryDPushButton)
        veterinary.setTabOrder(self.entryDPushButton, self.editDPushButton)
        veterinary.setTabOrder(self.editDPushButton, self.deleteDPushButton)
        veterinary.setTabOrder(self.deleteDPushButton, self.registerDTableWidget)
        veterinary.setTabOrder(self.registerDTableWidget, self.chatTextBrowser)
        veterinary.setTabOrder(self.chatTextBrowser, self.chatLineEdit)

    def retranslateUi(self, veterinary):
        veterinary.setWindowTitle(_translate("veterinary", "Veterinaria", None))
        item = self.registerCTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("veterinary", "Nombre", None))
        item = self.registerCTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("veterinary", "Apellido1", None))
        item = self.registerCTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("veterinary", "Apellido2", None))
        item = self.registerCTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("veterinary", "Direccion", None))
        item = self.registerCTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("veterinary", "Celular", None))
        item = self.registerCTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("veterinary", "C.P", None))
        item = self.registerCTableWidget.horizontalHeaderItem(6)
        item.setText(_translate("veterinary", "E-mail", None))
        item = self.registerCTableWidget.horizontalHeaderItem(7)
        item.setText(_translate("veterinary", "Telefono", None))
        item = self.registerCTableWidget.horizontalHeaderItem(8)
        item.setText(_translate("veterinary", "ID", None))
        self.label_18.setText(_translate("veterinary", "Nombre", None))
        self.nameCLineEdit.setText(_translate("veterinary", "Nombre", None))
        self.label_5.setText(_translate("veterinary", "C.P.", None))
        self.cpCLineEdit.setText(_translate("veterinary", "C.P.", None))
        self.entryCPushButton.setText(_translate("veterinary", "Ingresar", None))
        self.lastname1CLineEdit.setText(_translate("veterinary", "Apellido 1", None))
        self.label_17.setText(_translate("veterinary", "Apellido 1", None))
        self.emailCLineEdit.setText(_translate("veterinary", "E-mail", None))
        self.label_6.setText(_translate("veterinary", "E-mail", None))
        self.label_3.setText(_translate("veterinary", "Apellido 2", None))
        self.lastname2CLineEdit.setText(_translate("veterinary", "Apellido 2", None))
        self.phoneCLineEdit.setText(_translate("veterinary", "Telefono", None))
        self.label_7.setText(_translate("veterinary", "Telefono", None))
        self.addressCLineEdit.setText(_translate("veterinary", "Direccion", None))
        self.label_4.setText(_translate("veterinary", "Direccion", None))
        self.celphoneCLineEdit.setText(_translate("veterinary", "Celular", None))
        self.label_9.setText(_translate("veterinary", "Celular", None))
        self.searchCLineEdit.setText(_translate("veterinary", "Buscar", None))
        self.editCPushButton.setText(_translate("veterinary", "Editar", None))
        self.deleteCPushButton.setText(_translate("veterinary", "Eliminar", None))
        self.clearCPushButton.setText(_translate("veterinary", "Limpiar", None))
        self.TabWidget_4.setTabText(self.TabWidget_4.indexOf(self.tab_1), _translate("veterinary", "Registro Clientes", None))
        self.ageDLineEdit.setText(_translate("veterinary", "Edad", None))
        self.entryDPushButton.setText(_translate("veterinary", "Ingresar", None))
        self.deleteDPushButton.setText(_translate("veterinary", "Eliminar", None))
        self.raceDLineEdit.setText(_translate("veterinary", "Raza", None))
        self.genderDLineEdit.setText(_translate("veterinary", "Sexo", None))
        self.editDPushButton.setText(_translate("veterinary", "Editar", None))
        self.uploadDPushButton.setText(_translate("veterinary", "Subir", None))
        item = self.registerDTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("veterinary", "Nombre", None))
        item = self.registerDTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("veterinary", "Raza", None))
        item = self.registerDTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("veterinary", "Edad", None))
        item = self.registerDTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("veterinary", "Sexo", None))
        item = self.registerDTableWidget.horizontalHeaderItem(4)
        item.setText(_translate("veterinary", "Dueño", None))
        item = self.registerDTableWidget.horizontalHeaderItem(5)
        item.setText(_translate("veterinary", "ID perro", None))
        self.searchDLineEdit.setText(_translate("veterinary", "Buscar", None))
        self.nameDogDLineEdit.setText(_translate("veterinary", "Nombre", None))
        self.clearDPushButton.setText(_translate("veterinary", "Limpiar", None))
        self.TabWidget_4.setTabText(self.TabWidget_4.indexOf(self.tab_2), _translate("veterinary", "Registro de Perros", None))
        self.TabWidget_4.setTabText(self.TabWidget_4.indexOf(self.tab_3), _translate("veterinary", "Chat", None))
        self.actionCerrar_sesion.setText(_translate("veterinary", "Cerrar sesion", None))
        self.actionCerrar.setText(_translate("veterinary", "Cerrar", None))


class veterinary(QtGui.QMainWindow, Ui_veterinary):
    def __init__(self, parent=None, f=QtCore.Qt.WindowFlags()):
        QtGui.QMainWindow.__init__(self, parent, f)

        self.setupUi(self)

